title:            Vernon R. King, III
tagline:          He must become greater, I must become less.
description:      A collection of writings and updates from Vernon R. King, III.
#Comment out url when working locally to resolve base urls correctly
#url: http://vernonking.org/

# Owner/author information
owner:
  name:           Vernon R. King, III
  avatar:         avatar.png
  bio:            Follower of Jesus. Husband to Katie. Father to many. Student at Southeastern Baptist Theological Seminary.
  email:          mail@vernonking.org
  twitter:        vrking3
  github:         pjking07
  facebook:       pjking07
#  instagram:      ctrunsthis     
#  dribbble:       coletownsend
#  disqus:         balzac
  

# Links to include in top navigation
# For external links add external: true
links:
  - title: CV
    url: /cv
  - title: Archives
    url: /archives
  - title: Papers
    url: /papers
  - title: Reviews
    url: /reviews

# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone:    America/New_York
lsi:         false
future:      false
pygments:    true
markdown:    kramdown
redcarpet:
  extensions: ['smart', 'tables', 'no_intra_emphasis', 'autolink']
kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  use_coderay: false
  coderay:
    coderay_line_numbers: 
    coderay_line_numbers_start: 1
    coderay_tab_width: 4
    coderay_bold_every: 10
    coderay_css: class

# https://github.com/mojombo/jekyll/wiki/Permalinks
permalink:   /:categories/:title
relative_permalinks: false

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp"]
