title:            Vernon R. King, III
description:      "A collection of writings and updates from Vernon R. King, III: Follower of Jesus. Husband to Katie. Father to many. Student at SEBTS."
url: //vernonking.org/
files: //vernonking.org/files

# Owner/author information
owner:
  name:           Vernon R. King, III
  email:          mail@vernonking.org
  twitter:        vrking3
  github:         pjking07
  facebook:       pjking07

# Links to include in top navigation
# For external links add external: true
links:
  - title: CV
    url: /cv
  - title: Papers
    url: /papers
  - title: Reviews
    url: /reviews
  - title: Archives
    url: /archives

# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone:    America/New_York
lsi:         true
future:      false
pygments:    true
markdown:    kramdown
redcarpet:
  extensions: ['smart', 'tables', 'no_intra_emphasis', 'autolink']
kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  use_coderay: false
  coderay:
    coderay_line_numbers: 
    coderay_line_numbers_start: 1
    coderay_tab_width: 4
    coderay_bold_every: 10
    coderay_css: class

# https://github.com/mojombo/jekyll/wiki/Permalinks
permalink:   /:categories/:title
relative_permalinks: false

archive:
    month_format: "%Y-%b"

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp"]
